limit_req_zone $binary_remote_addr zone=opd_auth:10m rate=5r/m;

server {
    listen 80;
    listen [::]:80;
    server_name AWS_HOSTNAME;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
