"""S7: intake client_id + tree_ref for offline sync

Two columns the offline kiosk (doc 01 §5) needs on an intake:

* **client_id** — the kiosk's own id for an intake it completed during an
  outage, and the idempotency key for `POST /kiosk/sync`. The network typically
  returns *during* a batch, so a retry re-sends intakes that already landed;
  the unique index is what makes that a no-op instead of a second visit for one
  patient. Nullable and null for everything created online — a server-side
  intake never needs one — so the index is unique over the offline ones only.

* **tree_ref** — `key@vN` of the tree that produced `answers`. Node ids are
  stable across versions by design, so the same answers JSONB means different
  questions depending on which version was asked. S18 can publish a new version
  while a kiosk is offline with the old one cached in IndexedDB, which makes
  "which tree was this?" unanswerable without recording it.

Both are additive and nullable: no backfill, and existing intakes stay valid.

Revision ID: bc2e83129ac3
Revises: fbcaee31fa43
Create Date: 2026-07-17 18:57:11.044491

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc2e83129ac3'
down_revision: str | Sequence[str] | None = 'fbcaee31fa43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intakes', sa.Column('tree_ref', sa.String(length=120), nullable=True))
    op.add_column('intakes', sa.Column('client_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_intakes_client_id'), 'intakes', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intakes_client_id'), table_name='intakes')
    op.drop_column('intakes', 'client_id')
    op.drop_column('intakes', 'tree_ref')
    # ### end Alembic commands ###
