"""mrd: scanned documents and their extractions

Two new tables, nothing touched. No existing row changes meaning and no backfill
runs: a patient with no scans simply has no documents, which is what every
patient is until a coordinator points a phone at a report.

`document_extractions.document_id` is unique — one machine reading per document,
replaced in place when it is re-run. The pages it was read from live in the
object store, not here (`app/providers/objectstore.py`), so restoring this
database without also restoring that directory gives you extractions pointing at
pages that no longer exist. That is an operator fact, recorded in the deploy
note; the schema cannot enforce it.

Revision ID: efb79a43afb3
Revises: c063fd91e198
Create Date: 2026-08-05 23:39:24.637746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb79a43afb3'
down_revision: Union[str, Sequence[str], None] = 'c063fd91e198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_documents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('lab', 'histopath', 'imaging_report', 'discharge', 'outside_rx', 'other', name='document_kind', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('capturing', 'captured', 'extracting', 'extracted', 'summarized', 'extraction_failed', name='document_status', native_enum=False), nullable=False),
    sa.Column('object_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('captured_by', sa.UUID(), nullable=True),
    sa.Column('provider_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], name=op.f('fk_medical_documents_captured_by_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medical_documents_patient_id_patients')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_medical_documents_visit_id_visits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_documents'))
    )
    op.create_index(op.f('ix_medical_documents_captured_by'), 'medical_documents', ['captured_by'], unique=False)
    op.create_index(op.f('ix_medical_documents_patient_id'), 'medical_documents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_documents_status'), 'medical_documents', ['status'], unique=False)
    op.create_index(op.f('ix_medical_documents_visit_id'), 'medical_documents', ['visit_id'], unique=False)
    op.create_table('document_extractions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('outlier_count', sa.Integer(), nullable=False),
    sa.Column('prompt_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['medical_documents.id'], name=op.f('fk_document_extractions_document_id_medical_documents')),
    sa.ForeignKeyConstraint(['verified_by'], ['doctors.id'], name=op.f('fk_document_extractions_verified_by_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_extractions'))
    )
    op.create_index(op.f('ix_document_extractions_document_id'), 'document_extractions', ['document_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_extractions_document_id'), table_name='document_extractions')
    op.drop_table('document_extractions')
    op.drop_index(op.f('ix_medical_documents_visit_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_status'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_patient_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_captured_by'), table_name='medical_documents')
    op.drop_table('medical_documents')
    # ### end Alembic commands ###
