"""clinical notes: ambient observations, mapped and confirmed

One new table, nothing touched, no backfill: a visit with no observations simply
has no notes, which is what every visit is today.

Note what this table does *not* have, because it is the whole safety argument of
the module: there is no `meds` column, no formulary reference, no signature and
no foreign key to `prescriptions`. A consult note maps prose into S/O/A/P and
produces nothing downstream. `dictations` remains the only table whose signature
generates a prescription, and `app.notes` is pinned by a test that it does not
import `app.prescription` at all.

Unlike `dictations` there is no uniqueness on `visit_id` — several observations
per consult are expected, not a bug to be merged away.

Revision ID: 02571a5c1871
Revises: efb79a43afb3
Create Date: 2026-08-06 15:21:42.301294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02571a5c1871'
down_revision: Union[str, Sequence[str], None] = 'efb79a43afb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_notes',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', name='note_status', native_enum=False), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('provider_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['doctors.id'], name=op.f('fk_clinical_notes_confirmed_by_doctors')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_clinical_notes_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_clinical_notes_visit_id_visits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_notes'))
    )
    op.create_index(op.f('ix_clinical_notes_doctor_id'), 'clinical_notes', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_status'), 'clinical_notes', ['status'], unique=False)
    op.create_index(op.f('ix_clinical_notes_visit_id'), 'clinical_notes', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_notes_visit_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_status'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_doctor_id'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    # ### end Alembic commands ###
