"""departments care_system: the system of medicine, one flag

Additive, one column, **no backfill** — and the absence of a backfill is the
point rather than an omission. Every department that exists when this runs was
authored before the platform had a second system of medicine, so every one of
them genuinely is allopathy; the server default states that once and no UPDATE
has to assert it row by row.

`native_enum=False` with `create_constraint` off (SQLAlchemy 1.4+ default) makes
this a plain `varchar(9)` with no CHECK, so adding Unani or Homeopathy later is
a code change and not a migration. Nine characters is the ceiling: "homeopathy"
is ten and would need one.

Revision ID: 4ce8cb36a165
Revises: 8ef31aa60c55
Create Date: 2026-08-09 14:51:02.296771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce8cb36a165'
down_revision: Union[str, Sequence[str], None] = '8ef31aa60c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('care_system', sa.Enum('allopathy', 'ayurveda', name='care_system', native_enum=False), server_default='allopathy', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'care_system')
    # ### end Alembic commands ###
