"""hospital name_i18n: the hospital's name per pilot language

Additive, one column, server default, **no backfill** — an empty object is the
honest state for a facility nobody has translated yet, and `Hospital.name_in()`
falls back to `name`, which every existing row already has. So every surface
renders exactly what it rendered before this migration until somebody types a
translation into the admin console.

Revision ID: 28e0ff23658b
Revises: 4ce8cb36a165
Create Date: 2026-08-09 19:11:47.399681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28e0ff23658b'
down_revision: Union[str, Sequence[str], None] = '4ce8cb36a165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'name_i18n')
    # ### end Alembic commands ###
