"""patient allergies: the statement log behind the spine's third slot

One new table, nothing touched, no backfill — and the absence of a backfill is
the point. Every patient already in this database has no allergy statement on
file, which is exactly true: nobody has ever been asked. Inventing a `none_known`
row for them would turn "we never asked" into "she said no" for tens of thousands
of records at once, which is the single worst thing this migration could do.

Note what the table does *not* have. There is no `active` boolean and no unique
constraint on (patient, substance): this is an append-only log of statements, not
a list of current allergies, and the current picture is derived in
`app.allergies.for_patient`. Storing the derived state would give two places to
disagree about whether a patient is allergic to penicillin.

`none_known` is a row rather than an absence of rows, so that "asked and told
there are none" and "never asked" stay distinguishable at the storage layer and
not merely in the console's wording. Retraction is `retracted_at` + a doctor +
a reason, never a DELETE, because a record that silently loses a withdrawn
allergy cannot answer what it told the doctor who prescribed last month.

Revision ID: 8ef31aa60c55
Revises: 9f2ab41c77d3
Create Date: 2026-08-08 22:00:16.555122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef31aa60c55'
down_revision: Union[str, Sequence[str], None] = '9f2ab41c77d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_allergies',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('substance', 'none_known', name='allergy_kind', native_enum=False), nullable=False),
    sa.Column('substance', sa.String(length=200), nullable=True),
    sa.Column('substance_en', sa.String(length=200), nullable=True),
    sa.Column('reaction', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('unknown', 'mild', 'severe', name='allergy_severity', native_enum=False), server_default='unknown', nullable=False),
    sa.Column('source', sa.Enum('patient_kiosk', 'caregiver_kiosk', 'doctor', name='allergy_source', native_enum=False), nullable=False),
    sa.Column('recorded_by_doctor_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_by_doctor_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retracted_by_doctor_id', sa.UUID(), nullable=True),
    sa.Column('retracted_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_doctor_id'], ['doctors.id'], name=op.f('fk_patient_allergies_confirmed_by_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_allergies_patient_id_patients')),
    sa.ForeignKeyConstraint(['recorded_by_doctor_id'], ['doctors.id'], name=op.f('fk_patient_allergies_recorded_by_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['retracted_by_doctor_id'], ['doctors.id'], name=op.f('fk_patient_allergies_retracted_by_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_patient_allergies_visit_id_visits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_allergies'))
    )
    op.create_index(op.f('ix_patient_allergies_kind'), 'patient_allergies', ['kind'], unique=False)
    op.create_index(op.f('ix_patient_allergies_patient_id'), 'patient_allergies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_allergies_visit_id'), 'patient_allergies', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_allergies_visit_id'), table_name='patient_allergies')
    op.drop_index(op.f('ix_patient_allergies_patient_id'), table_name='patient_allergies')
    op.drop_index(op.f('ix_patient_allergies_kind'), table_name='patient_allergies')
    op.drop_table('patient_allergies')
    # ### end Alembic commands ###
