"""patient app: caregiver links, dose events, patient refresh sessions

Revision ID: e108276e7d43
Revises: 48da92857b2a
Create Date: 2026-07-25 23:19:19.760449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e108276e7d43'
down_revision: Union[str, Sequence[str], None] = '48da92857b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_links',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('relation', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('invited', 'active', 'revoked', name='caregiver_link_status', native_enum=False), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_caregiver_links_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_caregiver_links')),
    sa.UniqueConstraint('patient_id', 'phone', name='uq_caregiver_links_patient_id_phone')
    )
    op.create_index(op.f('ix_caregiver_links_patient_id'), 'caregiver_links', ['patient_id'], unique=False)
    op.create_index(op.f('ix_caregiver_links_phone'), 'caregiver_links', ['phone'], unique=False)
    op.create_index(op.f('ix_caregiver_links_status'), 'caregiver_links', ['status'], unique=False)
    op.create_table('dose_events',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('med_index', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('taken', 'missed', 'snoozed', name='dose_status', native_enum=False), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('caregiver_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_dose_events_patient_id_patients')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_dose_events_prescription_id_prescriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dose_events')),
    sa.UniqueConstraint('prescription_id', 'med_index', 'scheduled_for', name='uq_dose_events_prescription_id_med_index_scheduled_for')
    )
    op.create_index(op.f('ix_dose_events_patient_id'), 'dose_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_dose_events_prescription_id'), 'dose_events', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_dose_events_scheduled_for'), 'dose_events', ['scheduled_for'], unique=False)
    # server_default on the way in, so the NOT NULL can land on a table that
    # already has rows; the column is application-defaulted from here on.
    op.add_column(
        'intakes',
        sa.Column('caregiver_answered', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('intakes', 'caregiver_answered', server_default=None)
    op.add_column('refresh_tokens', sa.Column('patient_id', sa.UUID(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('subject_phone', sa.String(length=20), nullable=True))
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_refresh_tokens_patient_id'), 'refresh_tokens', ['patient_id'], unique=False)
    op.create_foreign_key(op.f('fk_refresh_tokens_patient_id_patients'), 'refresh_tokens', 'patients', ['patient_id'], ['id'])
    # A refresh session belongs to a staff user or to a patient, never both and
    # never neither. Autogenerate does not diff CHECKs on existing tables, so
    # this one is written by hand — dropping it would let a rotation mint the
    # wrong audience's access token.
    op.create_check_constraint(
        'subject_exactly_one',
        'refresh_tokens',
        '(user_id IS NULL) <> (patient_id IS NULL)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_refresh_tokens_subject_exactly_one'), 'refresh_tokens', type_='check')
    op.drop_constraint(op.f('fk_refresh_tokens_patient_id_patients'), 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_patient_id'), table_name='refresh_tokens')
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('refresh_tokens', 'subject_phone')
    op.drop_column('refresh_tokens', 'patient_id')
    op.drop_column('intakes', 'caregiver_answered')
    op.drop_index(op.f('ix_dose_events_scheduled_for'), table_name='dose_events')
    op.drop_index(op.f('ix_dose_events_prescription_id'), table_name='dose_events')
    op.drop_index(op.f('ix_dose_events_patient_id'), table_name='dose_events')
    op.drop_table('dose_events')
    op.drop_index(op.f('ix_caregiver_links_status'), table_name='caregiver_links')
    op.drop_index(op.f('ix_caregiver_links_phone'), table_name='caregiver_links')
    op.drop_index(op.f('ix_caregiver_links_patient_id'), table_name='caregiver_links')
    op.drop_table('caregiver_links')
    # ### end Alembic commands ###
