"""initial schema

The full domain schema of doc 02 §4, plus the database-level enforcement of the
append-only audit log (doc 02 §7: "audit log immutable").

Revision ID: 75dc12335238
Revises:
Create Date: 2026-07-15 18:57:24.781922

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75dc12335238"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Append-only is enforced here rather than in the ORM: a Python-side guard only
# binds code that goes through the ORM, and an audit trail an admin can quietly
# edit from psql is not an audit trail. These triggers make UPDATE and DELETE on
# audit_log fail for every client, including superusers and future migrations.
# Rewriting history therefore requires dropping a trigger — a deliberate,
# visible act rather than a stray UPDATE.
#
# Retention/rotation (doc 02 §7 exports the log to S3 daily) must DROP the
# triggers, prune, and recreate them, in a migration that says so.
# One statement per entry: asyncpg sends DDL as a prepared statement, which
# rejects multi-command strings.
AUDIT_APPEND_ONLY_UP = [
    """
    CREATE OR REPLACE FUNCTION audit_log_reject_mutation() RETURNS trigger AS $$
    BEGIN
        RAISE EXCEPTION 'audit_log is append-only: % is not permitted', TG_OP
            USING ERRCODE = 'restrict_violation';
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER audit_log_no_update
        BEFORE UPDATE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_reject_mutation();
    """,
    """
    CREATE TRIGGER audit_log_no_delete
        BEFORE DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_reject_mutation();
    """,
    # TRUNCATE triggers are statement-level by definition — FOR EACH ROW is a
    # syntax error here.
    """
    CREATE TRIGGER audit_log_no_truncate
        BEFORE TRUNCATE ON audit_log
        FOR EACH STATEMENT EXECUTE FUNCTION audit_log_reject_mutation();
    """,
]

AUDIT_APPEND_ONLY_DOWN = [
    "DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log;",
    "DROP TRIGGER IF EXISTS audit_log_no_delete ON audit_log;",
    "DROP TRIGGER IF EXISTS audit_log_no_update ON audit_log;",
    "DROP FUNCTION IF EXISTS audit_log_reject_mutation();",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hospitals",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column(
            "default_lang",
            sa.Enum("en", "hi", "mr", "te", name="lang", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hospitals")),
        sa.UniqueConstraint("code", name=op.f("uq_hospitals_code")),
    )
    op.create_table(
        "otp_codes",
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "purpose", sa.Enum("login", name="otp_purpose", native_enum=False), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_codes")),
    )
    op.create_index(op.f("ix_otp_codes_expires_at"), "otp_codes", ["expires_at"], unique=False)
    op.create_index(op.f("ix_otp_codes_phone"), "otp_codes", ["phone"], unique=False)
    op.create_index(
        "ix_otp_codes_phone_created_at", "otp_codes", ["phone", "created_at"], unique=False
    )
    op.create_table(
        "price_book",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column(
            "unit",
            sa.Enum(
                "token_in",
                "token_out",
                "audio_sec",
                "call_min",
                "msg",
                name="price_unit",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("price_inr", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_book")),
        sa.UniqueConstraint(
            "provider", "model", "unit", "effective_from", name="uq_price_book_entry"
        ),
    )
    op.create_index(
        op.f("ix_price_book_effective_from"), "price_book", ["effective_from"], unique=False
    )
    op.create_index(op.f("ix_price_book_model"), "price_book", ["model"], unique=False)
    op.create_index(op.f("ix_price_book_provider"), "price_book", ["provider"], unique=False)
    op.create_table(
        "usage_events",
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("minute_bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("intake_id", sa.UUID(), nullable=True),
        sa.Column("visit_id", sa.UUID(), nullable=True),
        sa.Column(
            "channel",
            sa.Enum(
                "kiosk", "phone", "whatsapp", "app", "paper", name="channel", native_enum=False
            ),
            nullable=True,
        ),
        sa.Column(
            "tier",
            sa.Enum(
                "conversational",
                "rule_based",
                "prerecorded",
                "paper",
                name="intake_tier",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column(
            "purpose",
            sa.Enum(
                "intake_turn",
                "summary",
                "routing",
                "dictation",
                "checkin",
                "other",
                name="usage_purpose",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("audio_seconds", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit_cost_ref", sa.UUID(), nullable=True),
        sa.Column("computed_cost_inr", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_events")),
    )
    op.create_index(op.f("ix_usage_events_at"), "usage_events", ["at"], unique=False)
    op.create_index("ix_usage_events_intake_at", "usage_events", ["intake_id", "at"], unique=False)
    op.create_index(op.f("ix_usage_events_intake_id"), "usage_events", ["intake_id"], unique=False)
    op.create_index(
        op.f("ix_usage_events_minute_bucket"), "usage_events", ["minute_bucket"], unique=False
    )
    op.create_index(
        "ix_usage_events_minute_bucket_provider",
        "usage_events",
        ["minute_bucket", "provider"],
        unique=False,
    )
    op.create_index(op.f("ix_usage_events_provider"), "usage_events", ["provider"], unique=False)
    op.create_index(op.f("ix_usage_events_purpose"), "usage_events", ["purpose"], unique=False)
    op.create_index(
        op.f("ix_usage_events_session_id"), "usage_events", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_usage_events_visit_id"), "usage_events", ["visit_id"], unique=False)
    op.create_table(
        "departments",
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"], ["hospitals.id"], name=op.f("fk_departments_hospital_id_hospitals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("hospital_id", "code", name="uq_departments_hospital_code"),
    )
    op.create_index(
        op.f("ix_departments_hospital_id"), "departments", ["hospital_id"], unique=False
    )
    op.create_table(
        "patients",
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("mrn", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("alt_phone", sa.String(length=20), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column(
            "sex", sa.Enum("male", "female", "other", name="sex", native_enum=False), nullable=True
        ),
        sa.Column(
            "lang", sa.Enum("en", "hi", "mr", "te", name="lang", native_enum=False), nullable=False
        ),
        sa.Column("village", sa.String(length=120), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column("caregiver_name", sa.String(length=200), nullable=True),
        sa.Column("caregiver_phone", sa.String(length=20), nullable=True),
        sa.Column("consent_given_at", sa.Date(), nullable=True),
        sa.Column("consent_audio_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"], ["hospitals.id"], name=op.f("fk_patients_hospital_id_hospitals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
    )
    op.create_index(op.f("ix_patients_hospital_id"), "patients", ["hospital_id"], unique=False)
    op.create_index(op.f("ix_patients_mrn"), "patients", ["mrn"], unique=True)
    op.create_index(op.f("ix_patients_phone"), "patients", ["phone"], unique=False)
    op.create_table(
        "users",
        sa.Column("hospital_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "patient",
                "caregiver",
                "coordinator",
                "nurse",
                "doctor",
                "admin",
                name="role",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "lang", sa.Enum("en", "hi", "mr", "te", name="lang", native_enum=False), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("totp_secret", sa.String(length=64), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"], ["hospitals.id"], name=op.f("fk_users_hospital_id_hospitals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index(op.f("ix_users_hospital_id"), "users", ["hospital_id"], unique=False)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "actor_role",
            sa.Enum(
                "patient",
                "caregiver",
                "coordinator",
                "nurse",
                "doctor",
                "admin",
                name="role",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("actor_label", sa.String(length=120), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "create", "update", "soft_delete", "delete", name="audit_action", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_log_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False)
    op.create_index("ix_audit_log_actor_id_at", "audit_log", ["actor_id", "at"], unique=False)
    op.create_index(op.f("ix_audit_log_at"), "audit_log", ["at"], unique=False)
    op.create_index(op.f("ix_audit_log_entity"), "audit_log", ["entity"], unique=False)
    op.create_index(
        "ix_audit_log_entity_entity_id", "audit_log", ["entity", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_entity_id"), "audit_log", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_log_request_id"), "audit_log", ["request_id"], unique=False)
    op.create_table(
        "doctors",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("reg_no", sa.String(length=64), nullable=False),
        sa.Column("qualification", sa.String(length=200), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name=op.f("fk_doctors_department_id_departments")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_doctors_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctors")),
        sa.UniqueConstraint("reg_no", name=op.f("uq_doctors_reg_no")),
    )
    op.create_index(op.f("ix_doctors_department_id"), "doctors", ["department_id"], unique=False)
    op.create_index(op.f("ix_doctors_phone"), "doctors", ["phone"], unique=False)
    op.create_index(op.f("ix_doctors_user_id"), "doctors", ["user_id"], unique=True)
    op.create_table(
        "offline_token_blocks",
        sa.Column("kiosk_id", sa.String(length=64), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_no", sa.Integer(), nullable=False),
        sa.Column("end_no", sa.Integer(), nullable=False),
        sa.Column("used_up_to", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_offline_token_blocks_department_id_departments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offline_token_blocks")),
        sa.UniqueConstraint(
            "kiosk_id", "date", "start_no", name="uq_offline_blocks_kiosk_date_start"
        ),
    )
    op.create_index(
        op.f("ix_offline_token_blocks_date"), "offline_token_blocks", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_offline_token_blocks_department_id"),
        "offline_token_blocks",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_token_blocks_kiosk_id"), "offline_token_blocks", ["kiosk_id"], unique=False
    )
    op.create_table(
        "question_trees",
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "lang", sa.Enum("en", "hi", "mr", "te", name="lang", native_enum=False), nullable=False
        ),
        sa.Column("tree", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", name="tree_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_question_trees_department_id_departments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_trees")),
        sa.UniqueConstraint("key", "lang", "version", name="uq_question_trees_key_lang_version"),
    )
    op.create_index(
        op.f("ix_question_trees_department_id"), "question_trees", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_question_trees_key"), "question_trees", ["key"], unique=False)
    op.create_index(op.f("ix_question_trees_status"), "question_trees", ["status"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_jti"), "refresh_tokens", ["jti"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "appointments",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("doctor_id", sa.UUID(), nullable=True),
        sa.Column("slot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "booked",
                "confirmed",
                "rescheduled",
                "cancelled",
                "arrived",
                name="appointment_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "kiosk", "phone", "whatsapp", "app", "paper", name="channel", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("reminders", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_appointments_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"], ["doctors.id"], name=op.f("fk_appointments_doctor_id_doctors")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_appointments_patient_id_patients")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    op.create_index(
        op.f("ix_appointments_department_id"), "appointments", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_appointments_doctor_id"), "appointments", ["doctor_id"], unique=False)
    op.create_index(
        op.f("ix_appointments_patient_id"), "appointments", ["patient_id"], unique=False
    )
    op.create_index(op.f("ix_appointments_slot_at"), "appointments", ["slot_at"], unique=False)
    op.create_index(op.f("ix_appointments_status"), "appointments", ["status"], unique=False)
    op.create_table(
        "queues",
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("doctor_id", sa.UUID(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name=op.f("fk_queues_department_id_departments")
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"], ["doctors.id"], name=op.f("fk_queues_doctor_id_doctors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queues")),
        sa.UniqueConstraint(
            "department_id", "doctor_id", "date", name="uq_queues_dept_doctor_date"
        ),
    )
    op.create_index(op.f("ix_queues_date"), "queues", ["date"], unique=False)
    op.create_index(op.f("ix_queues_department_id"), "queues", ["department_id"], unique=False)
    op.create_index(op.f("ix_queues_doctor_id"), "queues", ["doctor_id"], unique=False)
    op.create_table(
        "visits",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("doctor_id", sa.UUID(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("token_no", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "registered",
                "intake_done",
                "in_queue",
                "in_consult",
                "done",
                "no_show",
                name="visit_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "kiosk", "phone", "whatsapp", "app", "paper", name="channel", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name=op.f("fk_visits_department_id_departments")
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"], ["doctors.id"], name=op.f("fk_visits_doctor_id_doctors")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_visits_patient_id_patients")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visits")),
        sa.UniqueConstraint("department_id", "date", "token_no", name="uq_visits_dept_date_token"),
    )
    op.create_index(op.f("ix_visits_date"), "visits", ["date"], unique=False)
    op.create_index(op.f("ix_visits_department_id"), "visits", ["department_id"], unique=False)
    op.create_index(op.f("ix_visits_doctor_id"), "visits", ["doctor_id"], unique=False)
    op.create_index(op.f("ix_visits_patient_id"), "visits", ["patient_id"], unique=False)
    op.create_index(op.f("ix_visits_status"), "visits", ["status"], unique=False)
    op.create_table(
        "checkin_plans",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("visit_id", sa.UUID(), nullable=True),
        sa.Column("protocol_key", sa.String(length=64), nullable=False),
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "approved",
                "active",
                "completed",
                "cancelled",
                name="checkin_plan_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["doctors.id"], name=op.f("fk_checkin_plans_approved_by_doctors")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_checkin_plans_patient_id_patients")
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"], ["visits.id"], name=op.f("fk_checkin_plans_visit_id_visits")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkin_plans")),
    )
    op.create_index(
        op.f("ix_checkin_plans_patient_id"), "checkin_plans", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_checkin_plans_protocol_key"), "checkin_plans", ["protocol_key"], unique=False
    )
    op.create_index(op.f("ix_checkin_plans_status"), "checkin_plans", ["status"], unique=False)
    op.create_index(op.f("ix_checkin_plans_visit_id"), "checkin_plans", ["visit_id"], unique=False)
    op.create_table(
        "dictations",
        sa.Column("visit_id", sa.UUID(), nullable=False),
        sa.Column("doctor_id", sa.UUID(), nullable=False),
        sa.Column("audio_url", sa.String(length=500), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("structured", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "signed", name="dictation_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signed_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"], ["doctors.id"], name=op.f("fk_dictations_doctor_id_doctors")
        ),
        sa.ForeignKeyConstraint(
            ["signed_by"], ["doctors.id"], name=op.f("fk_dictations_signed_by_doctors")
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"], ["visits.id"], name=op.f("fk_dictations_visit_id_visits")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dictations")),
    )
    op.create_index(op.f("ix_dictations_doctor_id"), "dictations", ["doctor_id"], unique=False)
    op.create_index(op.f("ix_dictations_status"), "dictations", ["status"], unique=False)
    op.create_index(op.f("ix_dictations_visit_id"), "dictations", ["visit_id"], unique=False)
    op.create_table(
        "intakes",
        sa.Column("visit_id", sa.UUID(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "conversational",
                "rule_based",
                "prerecorded",
                "paper",
                name="intake_tier",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "lang", sa.Enum("en", "hi", "mr", "te", name="lang", native_enum=False), nullable=False
        ),
        sa.Column("transcript", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("red_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("chief_complaint", sa.Text(), nullable=True),
        sa.Column("chief_complaint_en", sa.Text(), nullable=True),
        sa.Column("summary_md", sa.Text(), nullable=True),
        sa.Column("summary_lang_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirmed_by_patient", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost_inr", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["visit_id"], ["visits.id"], name=op.f("fk_intakes_visit_id_visits")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intakes")),
    )
    op.create_index(op.f("ix_intakes_visit_id"), "intakes", ["visit_id"], unique=False)
    op.create_table(
        "queue_entries",
        sa.Column("queue_id", sa.UUID(), nullable=False),
        sa.Column("visit_id", sa.UUID(), nullable=False),
        sa.Column("token_no", sa.Integer(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("routine", "semi", "urgent", name="priority", native_enum=False),
            nullable=False,
        ),
        sa.Column("priority_reason", sa.String(length=200), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "waiting",
                "called",
                "in_consult",
                "done",
                "no_show",
                "lab_requeue",
                name="queue_entry_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("called_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["queue_id"], ["queues.id"], name=op.f("fk_queue_entries_queue_id_queues")
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"], ["visits.id"], name=op.f("fk_queue_entries_visit_id_visits")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queue_entries")),
        sa.UniqueConstraint("queue_id", "visit_id", name="uq_queue_entries_queue_visit"),
    )
    op.create_index(op.f("ix_queue_entries_queue_id"), "queue_entries", ["queue_id"], unique=False)
    op.create_index(op.f("ix_queue_entries_state"), "queue_entries", ["state"], unique=False)
    op.create_index(op.f("ix_queue_entries_visit_id"), "queue_entries", ["visit_id"], unique=False)
    op.create_table(
        "checkins",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "kiosk", "phone", "whatsapp", "app", "paper", name="channel", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "grade",
            sa.Enum("green", "amber", "red", name="checkin_grade", native_enum=False),
            nullable=True,
        ),
        sa.Column("escalated_to", sa.UUID(), nullable=True),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["escalated_to"], ["users.id"], name=op.f("fk_checkins_escalated_to_users")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["checkin_plans.id"], name=op.f("fk_checkins_plan_id_checkin_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkins")),
    )
    op.create_index(op.f("ix_checkins_due_at"), "checkins", ["due_at"], unique=False)
    op.create_index(op.f("ix_checkins_grade"), "checkins", ["grade"], unique=False)
    op.create_index(op.f("ix_checkins_plan_id"), "checkins", ["plan_id"], unique=False)
    op.create_table(
        "prescriptions",
        sa.Column("visit_id", sa.UUID(), nullable=False),
        sa.Column("dictation_id", sa.UUID(), nullable=True),
        sa.Column("meds", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("delivered_via", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["dictation_id"],
            ["dictations.id"],
            name=op.f("fk_prescriptions_dictation_id_dictations"),
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"], ["visits.id"], name=op.f("fk_prescriptions_visit_id_visits")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prescriptions")),
    )
    op.create_index(
        op.f("ix_prescriptions_dictation_id"), "prescriptions", ["dictation_id"], unique=False
    )
    op.create_index(op.f("ix_prescriptions_visit_id"), "prescriptions", ["visit_id"], unique=False)
    # ### end Alembic commands ###
    for statement in AUDIT_APPEND_ONLY_UP:
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    for statement in AUDIT_APPEND_ONLY_DOWN:
        op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prescriptions_visit_id"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_dictation_id"), table_name="prescriptions")
    op.drop_table("prescriptions")
    op.drop_index(op.f("ix_checkins_plan_id"), table_name="checkins")
    op.drop_index(op.f("ix_checkins_grade"), table_name="checkins")
    op.drop_index(op.f("ix_checkins_due_at"), table_name="checkins")
    op.drop_table("checkins")
    op.drop_index(op.f("ix_queue_entries_visit_id"), table_name="queue_entries")
    op.drop_index(op.f("ix_queue_entries_state"), table_name="queue_entries")
    op.drop_index(op.f("ix_queue_entries_queue_id"), table_name="queue_entries")
    op.drop_table("queue_entries")
    op.drop_index(op.f("ix_intakes_visit_id"), table_name="intakes")
    op.drop_table("intakes")
    op.drop_index(op.f("ix_dictations_visit_id"), table_name="dictations")
    op.drop_index(op.f("ix_dictations_status"), table_name="dictations")
    op.drop_index(op.f("ix_dictations_doctor_id"), table_name="dictations")
    op.drop_table("dictations")
    op.drop_index(op.f("ix_checkin_plans_visit_id"), table_name="checkin_plans")
    op.drop_index(op.f("ix_checkin_plans_status"), table_name="checkin_plans")
    op.drop_index(op.f("ix_checkin_plans_protocol_key"), table_name="checkin_plans")
    op.drop_index(op.f("ix_checkin_plans_patient_id"), table_name="checkin_plans")
    op.drop_table("checkin_plans")
    op.drop_index(op.f("ix_visits_status"), table_name="visits")
    op.drop_index(op.f("ix_visits_patient_id"), table_name="visits")
    op.drop_index(op.f("ix_visits_doctor_id"), table_name="visits")
    op.drop_index(op.f("ix_visits_department_id"), table_name="visits")
    op.drop_index(op.f("ix_visits_date"), table_name="visits")
    op.drop_table("visits")
    op.drop_index(op.f("ix_queues_doctor_id"), table_name="queues")
    op.drop_index(op.f("ix_queues_department_id"), table_name="queues")
    op.drop_index(op.f("ix_queues_date"), table_name="queues")
    op.drop_table("queues")
    op.drop_index(op.f("ix_appointments_status"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_slot_at"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_patient_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_doctor_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_department_id"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_jti"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_question_trees_status"), table_name="question_trees")
    op.drop_index(op.f("ix_question_trees_key"), table_name="question_trees")
    op.drop_index(op.f("ix_question_trees_department_id"), table_name="question_trees")
    op.drop_table("question_trees")
    op.drop_index(op.f("ix_offline_token_blocks_kiosk_id"), table_name="offline_token_blocks")
    op.drop_index(op.f("ix_offline_token_blocks_department_id"), table_name="offline_token_blocks")
    op.drop_index(op.f("ix_offline_token_blocks_date"), table_name="offline_token_blocks")
    op.drop_table("offline_token_blocks")
    op.drop_index(op.f("ix_doctors_user_id"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_phone"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_department_id"), table_name="doctors")
    op.drop_table("doctors")
    op.drop_index(op.f("ix_audit_log_request_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entity_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_entity_entity_id", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entity"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_at"), table_name="audit_log")
    op.drop_index("ix_audit_log_actor_id_at", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_hospital_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_patients_phone"), table_name="patients")
    op.drop_index(op.f("ix_patients_mrn"), table_name="patients")
    op.drop_index(op.f("ix_patients_hospital_id"), table_name="patients")
    op.drop_table("patients")
    op.drop_index(op.f("ix_departments_hospital_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_usage_events_visit_id"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_session_id"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_purpose"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_provider"), table_name="usage_events")
    op.drop_index("ix_usage_events_minute_bucket_provider", table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_minute_bucket"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_intake_id"), table_name="usage_events")
    op.drop_index("ix_usage_events_intake_at", table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_at"), table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_index(op.f("ix_price_book_provider"), table_name="price_book")
    op.drop_index(op.f("ix_price_book_model"), table_name="price_book")
    op.drop_index(op.f("ix_price_book_effective_from"), table_name="price_book")
    op.drop_table("price_book")
    op.drop_index("ix_otp_codes_phone_created_at", table_name="otp_codes")
    op.drop_index(op.f("ix_otp_codes_phone"), table_name="otp_codes")
    op.drop_index(op.f("ix_otp_codes_expires_at"), table_name="otp_codes")
    op.drop_table("otp_codes")
    op.drop_table("hospitals")
    # ### end Alembic commands ###
