"""s_gl1 channel configs and provider secrets

Revision ID: 2c978d44c900
Revises: cb011d62f829
Create Date: 2026-07-26 17:58:50.281255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c978d44c900'
down_revision: Union[str, Sequence[str], None] = 'cb011d62f829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_configs',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='tree_status', native_enum=False), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_configs')),
    sa.UniqueConstraint('version', name='uq_channel_configs_version')
    )
    op.create_index(op.f('ix_channel_configs_status'), 'channel_configs', ['status'], unique=False)
    op.create_index(op.f('ix_channel_configs_version'), 'channel_configs', ['version'], unique=False)
    op.create_table('provider_secrets',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('last_test', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_provider_secrets_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_secrets')),
    sa.UniqueConstraint('provider', name='uq_provider_secrets_provider')
    )
    op.create_index(op.f('ix_provider_secrets_provider'), 'provider_secrets', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_secrets_provider'), table_name='provider_secrets')
    op.drop_table('provider_secrets')
    op.drop_index(op.f('ix_channel_configs_version'), table_name='channel_configs')
    op.drop_index(op.f('ix_channel_configs_status'), table_name='channel_configs')
    op.drop_table('channel_configs')
    # ### end Alembic commands ###
