"""S15: slot inventory, appointment seats, outbound calls

Three new tables and three additive columns behind doc 03 §2's "double-booking
impossible (DB constraint)":

- `slot_templates` — a doctor's recurring weekly clinic (the authored thing).
- `appointment_slots` — the generated bookable instants. Unique per
  (doctor, starts_at), with `CHECK (booked >= 0 AND booked <= capacity)`: the
  database itself refuses an overbooked clinic, whoever wrote the service code.
- `appointments.slot_id` / `seat_no` / `slot_type` — a booking now holds a
  numbered seat, `UNIQUE (slot_id, seat_no)`. Nullable throughout, so every
  pre-S15 appointment stays valid with no backfill; cancelling NULLs `seat_no`
  (NULLs do not collide in a Postgres unique index) to release the seat.
- `outbound_calls` — the D-1 campaign's retry ladder, unique per
  (appointment, purpose) so re-running the beat job re-dials nobody.

Revision ID: 48da92857b2a
Revises: a1b2c3d4e5f6
Create Date: 2026-07-25 18:21:33.905990

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48da92857b2a"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slot_templates",
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("doctor_id", sa.UUID(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("slot_minutes", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "slot_type",
            sa.Enum(
                "new_consult", "follow_up", "chemo_review", name="slot_type", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_slot_templates_capacity_positive")),
        sa.CheckConstraint(
            "slot_minutes > 0", name=op.f("ck_slot_templates_slot_minutes_positive")
        ),
        sa.CheckConstraint(
            "weekday >= 0 AND weekday <= 6", name=op.f("ck_slot_templates_weekday_in_week")
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_slot_templates_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"], ["doctors.id"], name=op.f("fk_slot_templates_doctor_id_doctors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_slot_templates")),
        sa.UniqueConstraint(
            "doctor_id",
            "weekday",
            "start_time",
            "slot_type",
            name="uq_slot_templates_doctor_weekday_start_type",
        ),
    )
    op.create_index(
        op.f("ix_slot_templates_department_id"), "slot_templates", ["department_id"], unique=False
    )
    op.create_index(
        op.f("ix_slot_templates_doctor_id"), "slot_templates", ["doctor_id"], unique=False
    )
    op.create_table(
        "appointment_slots",
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("doctor_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "slot_type",
            sa.Enum(
                "new_consult", "follow_up", "chemo_review", name="slot_type", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("booked", sa.Integer(), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "booked >= 0 AND booked <= capacity",
            name=op.f("ck_appointment_slots_booked_within_capacity"),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_appointment_slots_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"], ["doctors.id"], name=op.f("fk_appointment_slots_doctor_id_doctors")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["slot_templates.id"],
            name=op.f("fk_appointment_slots_template_id_slot_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointment_slots")),
        sa.UniqueConstraint("doctor_id", "starts_at", name="uq_appointment_slots_doctor_starts_at"),
    )
    op.create_index(
        op.f("ix_appointment_slots_department_id"),
        "appointment_slots",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointment_slots_doctor_id"), "appointment_slots", ["doctor_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointment_slots_slot_type"), "appointment_slots", ["slot_type"], unique=False
    )
    op.create_index(
        op.f("ix_appointment_slots_starts_at"), "appointment_slots", ["starts_at"], unique=False
    )
    op.create_table(
        "outbound_calls",
        sa.Column("appointment_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("for_date", sa.Date(), nullable=False),
        sa.Column("to_phone", sa.String(length=20), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "dialing",
                "completed",
                "failed",
                "fallback_sent",
                "cancelled",
                name="outbound_call_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_call_sid", sa.String(length=64), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("intake_id", sa.UUID(), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("fallback_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_outbound_calls_appointment_id_appointments"),
        ),
        sa.ForeignKeyConstraint(
            ["intake_id"], ["intakes.id"], name=op.f("fk_outbound_calls_intake_id_intakes")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_outbound_calls_patient_id_patients")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_calls")),
        sa.UniqueConstraint(
            "appointment_id", "purpose", name="uq_outbound_calls_appointment_purpose"
        ),
    )
    op.create_index(
        op.f("ix_outbound_calls_appointment_id"), "outbound_calls", ["appointment_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbound_calls_for_date"), "outbound_calls", ["for_date"], unique=False
    )
    op.create_index(
        op.f("ix_outbound_calls_last_call_sid"), "outbound_calls", ["last_call_sid"], unique=False
    )
    op.create_index(
        op.f("ix_outbound_calls_next_attempt_at"),
        "outbound_calls",
        ["next_attempt_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbound_calls_patient_id"), "outbound_calls", ["patient_id"], unique=False
    )
    op.create_index(op.f("ix_outbound_calls_state"), "outbound_calls", ["state"], unique=False)
    op.add_column("appointments", sa.Column("slot_id", sa.UUID(), nullable=True))
    op.add_column("appointments", sa.Column("seat_no", sa.Integer(), nullable=True))
    op.add_column(
        "appointments",
        sa.Column(
            "slot_type",
            sa.Enum(
                "new_consult", "follow_up", "chemo_review", name="slot_type", native_enum=False
            ),
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_appointments_slot_id"), "appointments", ["slot_id"], unique=False)
    op.create_unique_constraint(
        "uq_appointments_slot_id_seat_no", "appointments", ["slot_id", "seat_no"]
    )
    op.create_foreign_key(
        op.f("fk_appointments_slot_id_appointment_slots"),
        "appointments",
        "appointment_slots",
        ["slot_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_appointments_slot_id_appointment_slots"), "appointments", type_="foreignkey"
    )
    op.drop_constraint("uq_appointments_slot_id_seat_no", "appointments", type_="unique")
    op.drop_index(op.f("ix_appointments_slot_id"), table_name="appointments")
    op.drop_column("appointments", "slot_type")
    op.drop_column("appointments", "seat_no")
    op.drop_column("appointments", "slot_id")
    op.drop_index(op.f("ix_outbound_calls_state"), table_name="outbound_calls")
    op.drop_index(op.f("ix_outbound_calls_patient_id"), table_name="outbound_calls")
    op.drop_index(op.f("ix_outbound_calls_next_attempt_at"), table_name="outbound_calls")
    op.drop_index(op.f("ix_outbound_calls_last_call_sid"), table_name="outbound_calls")
    op.drop_index(op.f("ix_outbound_calls_for_date"), table_name="outbound_calls")
    op.drop_index(op.f("ix_outbound_calls_appointment_id"), table_name="outbound_calls")
    op.drop_table("outbound_calls")
    op.drop_index(op.f("ix_appointment_slots_starts_at"), table_name="appointment_slots")
    op.drop_index(op.f("ix_appointment_slots_slot_type"), table_name="appointment_slots")
    op.drop_index(op.f("ix_appointment_slots_doctor_id"), table_name="appointment_slots")
    op.drop_index(op.f("ix_appointment_slots_department_id"), table_name="appointment_slots")
    op.drop_table("appointment_slots")
    op.drop_index(op.f("ix_slot_templates_doctor_id"), table_name="slot_templates")
    op.drop_index(op.f("ix_slot_templates_department_id"), table_name="slot_templates")
    op.drop_table("slot_templates")
    # ### end Alembic commands ###
