"""visit conclusion: rx mode and how the consult ended

Additive only, and every column nullable with no backfill. Null `rx_mode` means
"not concluded", which is exactly what every existing visit is — a default of
`none` would have retroactively asserted that thousands of past consults ended
with no prescription, which is a clinical claim this migration is in no position
to make.

Revision ID: c063fd91e198
Revises: 520d07f0b3e4
Create Date: 2026-08-05 14:53:25.631689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c063fd91e198'
down_revision: Union[str, Sequence[str], None] = '520d07f0b3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('rx_mode', sa.Enum('system', 'external_manual', 'none', name='rx_mode', native_enum=False), nullable=True))
    op.add_column('visits', sa.Column('conclusion_note', sa.Text(), nullable=True))
    op.add_column('visits', sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('visits', sa.Column('concluded_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_visits_rx_mode'), 'visits', ['rx_mode'], unique=False)
    op.create_foreign_key(op.f('fk_visits_concluded_by_doctors'), 'visits', 'doctors', ['concluded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_visits_concluded_by_doctors'), 'visits', type_='foreignkey')
    op.drop_index(op.f('ix_visits_rx_mode'), table_name='visits')
    op.drop_column('visits', 'concluded_by')
    op.drop_column('visits', 'concluded_at')
    op.drop_column('visits', 'conclusion_note')
    op.drop_column('visits', 'rx_mode')
    # ### end Alembic commands ###
