"""protocol bank versions

Revision ID: cb011d62f829
Revises: ae3caebf5e9a
Create Date: 2026-07-26 10:12:36.162661

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb011d62f829"
down_revision: str | Sequence[str] | None = "ae3caebf5e9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "protocol_banks",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("bank", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", name="tree_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_protocol_banks")),
        sa.UniqueConstraint("version", name="uq_protocol_banks_version"),
    )
    op.create_index(op.f("ix_protocol_banks_status"), "protocol_banks", ["status"], unique=False)
    op.create_index(op.f("ix_protocol_banks_version"), "protocol_banks", ["version"], unique=False)
    # ### end Alembic commands ###

    # The other half of making the bank editable: freeze each check-in's grading
    # rules alongside its questions, so publishing a new bank cannot re-grade
    # answers a patient has already given. NULL on existing rows — they grade
    # against the bank exactly as they did before.
    op.add_column(
        "checkins",
        sa.Column("grading_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("checkins", "grading_rules")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_protocol_banks_version"), table_name="protocol_banks")
    op.drop_index(op.f("ix_protocol_banks_status"), table_name="protocol_banks")
    op.drop_table("protocol_banks")
    # ### end Alembic commands ###
