"""assignment identity: visit doctor link state, patient external id

Additive only. Every column is nullable or carries a server default, so this
migration is safe to apply to a running box ahead of the code that reads it and
needs no backfill.

`visits.doctor_id` is deliberately absent: the column has existed since the first
migration and was only ever written by the appointment path. Assignment starts
writing it; the schema does not change.

Revision ID: c6e3681f5ce1
Revises: a4d5e6f7b801
Create Date: 2026-08-04 22:39:31.256772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e3681f5ce1'
down_revision: Union[str, Sequence[str], None] = 'a4d5e6f7b801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.add_column('patients', sa.Column('external_id_kind', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_patients_external_id'), 'patients', ['external_id'], unique=False)
    op.add_column('visits', sa.Column('candidate_patient_id', sa.UUID(), nullable=True))
    op.add_column('visits', sa.Column('patient_link_state', sa.Enum('none', 'candidate', 'confirmed', 'rejected', name='patient_link_state', native_enum=False), server_default='none', nullable=False))
    op.create_index(op.f('ix_visits_candidate_patient_id'), 'visits', ['candidate_patient_id'], unique=False)
    op.create_index(op.f('ix_visits_patient_link_state'), 'visits', ['patient_link_state'], unique=False)
    op.create_foreign_key(op.f('fk_visits_candidate_patient_id_patients'), 'visits', 'patients', ['candidate_patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_visits_candidate_patient_id_patients'), 'visits', type_='foreignkey')
    op.drop_index(op.f('ix_visits_patient_link_state'), table_name='visits')
    op.drop_index(op.f('ix_visits_candidate_patient_id'), table_name='visits')
    op.drop_column('visits', 'patient_link_state')
    op.drop_column('visits', 'candidate_patient_id')
    op.drop_index(op.f('ix_patients_external_id'), table_name='patients')
    op.drop_column('patients', 'external_id_kind')
    op.drop_column('patients', 'external_id')
    # ### end Alembic commands ###
