"""kiosk staff pin on users

Revision ID: 520d07f0b3e4
Revises: c6e3681f5ce1
Create Date: 2026-08-04 22:53:25.913320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520d07f0b3e4'
down_revision: Union[str, Sequence[str], None] = 'c6e3681f5ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kiosk_pin_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('kiosk_pin_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('kiosk_pin_locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kiosk_pin_locked_until')
    op.drop_column('users', 'kiosk_pin_attempts')
    op.drop_column('users', 'kiosk_pin_hash')
    # ### end Alembic commands ###
